(define (sum term a next b)
  (if (> a b)
      0
      (+ (term a)
         (sum term (next a) next b))))

(define (cube x )
  (* x x x))

(define (sim f a b n)
  (define h (/ (- a b) n))
  (define (next x) (+ 1 x))
  (define (y k)
    (f (+ a (* k h))))
  (define (term k)
    (* (cond ((odd? k) 4)
             ((or (= k 0) (= k n)) 1)
             ((even? k) 2))
    (y k)))
  (/ (* h (sum term 0 next n)) 3))